#!/bin/bash
# Sets the app version in project.yml and commits it.
#
# CFBundleVersion (the build number) is incremented on its own: Apple requires
# it to grow with every upload, independently of the marketing version.
# App/Info.plist is generated by xcodegen from project.yml but committed, so
# both files are edited in place — running xcodegen here would need the frozen
# converter (~179 MB) present just to renumber two strings.
#
# Usage:
#   scripts/release/bump.sh 0.3.0   # explicit
#   scripts/release/bump.sh         # pick patch/minor/major interactively
#
# Re-running with the version already in project.yml is a no-op, so an
# interrupted release can be resumed.

set -euo pipefail
cd "$(dirname "$0")/../.."   # repo root

VERSION="${1:-}"

BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [[ "$BRANCH" != "main" && "${ALLOW_BRANCH:-0}" != "1" ]]; then
    echo "error: on branch '$BRANCH', releases are cut from main (ALLOW_BRANCH=1 to override)" >&2
    exit 1
fi
if [[ -n "$(git status --porcelain --untracked-files=no)" ]]; then
    echo "error: working tree has uncommitted changes — the bump commit would swallow them" >&2
    exit 1
fi
CURRENT=$(sed -nE 's/.*CFBundleShortVersionString: "(.*)".*/\1/p' project.yml | head -1)
BUILD=$(sed -nE 's/.*CFBundleVersion: "(.*)".*/\1/p' project.yml | head -1)
if [[ -z "$CURRENT" || -z "$BUILD" ]]; then
    echo "error: could not read the current version out of project.yml" >&2
    exit 1
fi

# No version given: offer the three bumps off the current one. The checks
# above run first, so an unusable tree is refused before anything is asked.
if [[ -z "$VERSION" ]]; then
    if [[ ! -t 0 ]]; then
        echo "error: no version given and no tty to ask on — pass one, e.g. $0 0.3.0" >&2
        exit 1
    fi
    IFS=. read -r major minor patch <<< "$CURRENT"
    PATCH_V="$major.$minor.$((patch + 1))"
    MINOR_V="$major.$((minor + 1)).0"
    MAJOR_V="$((major + 1)).0.0"
    echo "Current version: $CURRENT (build $BUILD)"
    echo "  1) patch   $PATCH_V"
    echo "  2) minor   $MINOR_V"
    echo "  3) major   $MAJOR_V"
    echo "  4) custom"
    read -r -p "Which one? [1] " choice
    case "${choice:-1}" in
        1|patch) VERSION="$PATCH_V" ;;
        2|minor) VERSION="$MINOR_V" ;;
        3|major) VERSION="$MAJOR_V" ;;
        4|custom) read -r -p "Version: " VERSION ;;
        *) echo "error: '$choice' is not one of 1-4" >&2; exit 1 ;;
    esac
fi

if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "error: version must look like 0.3.0 (got '$VERSION')" >&2
    exit 1
fi

if [[ "$CURRENT" == "$VERSION" ]]; then
    echo "==> project.yml is already at $VERSION (build $BUILD), nothing to bump"
    exit 0
fi

# Only relevant when there is something to bump: a re-run that finds the
# version already in place must stay a no-op.
if git rev-parse -q --verify "refs/tags/v$VERSION" >/dev/null; then
    echo "error: tag v$VERSION already exists — pick the next version" >&2
    exit 1
fi

NEXT_BUILD=$((BUILD + 1))
echo "==> $CURRENT (build $BUILD) -> $VERSION (build $NEXT_BUILD)"

# A half-renumbered tree is the dangerous outcome: the next run would read the
# new version out of project.yml and believe there is nothing left to do.
restore_and_fail() {
    git checkout -- project.yml App/Info.plist
    echo "error: $1 — project.yml and App/Info.plist restored" >&2
    exit 1
}

sed -i '' -E "s/(CFBundleShortVersionString: )\".*\"/\1\"$VERSION\"/" project.yml
sed -i '' -E "s/(CFBundleVersion: )\".*\"/\1\"$NEXT_BUILD\"/" project.yml
# PlistBuddy reports failures on stdout and still exits 0, so every edit is
# read back below rather than trusted.
/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $VERSION" App/Info.plist >/dev/null 2>&1 || true
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEXT_BUILD" App/Info.plist >/dev/null 2>&1 || true

plist_value() {
    /usr/libexec/PlistBuddy -c "Print :$1" App/Info.plist 2>/dev/null || echo ""
}
yaml_value() {
    sed -nE "s/.*$1: \"(.*)\".*/\\1/p" project.yml | head -1
}

[[ "$(yaml_value CFBundleShortVersionString)" == "$VERSION" ]] || restore_and_fail "project.yml was not updated"
[[ "$(yaml_value CFBundleVersion)" == "$NEXT_BUILD" ]] || restore_and_fail "project.yml build number was not updated"
[[ "$(plist_value CFBundleShortVersionString)" == "$VERSION" ]] || restore_and_fail "App/Info.plist was not updated"
[[ "$(plist_value CFBundleVersion)" == "$NEXT_BUILD" ]] || restore_and_fail "App/Info.plist build number was not updated"

git add project.yml App/Info.plist
git commit -q -m "chore: bump the app version to $VERSION"
echo "==> Committed: $(git log --oneline -1)"
